# world/gtfo/__init__.py

import math
import os
import json
import itertools as itertools
from collections.abc import Sequence
from typing import cast, Any, Callable, Dict, Set, List, Optional, TextIO, Union, Mapping

from BaseClasses import CollectionState, MultiWorld, Region, Item, Location, LocationProgressType, Entrance, Tutorial, ItemClassification

from worlds.AutoWorld import World, WebWorld
from worlds.generic import Rules
import settings
import Utils

from .options import GTFOOptions, gtfo_option_groups
from .moddedInstanceDataTypes import *


class GTFOItem(Item):
    game: str = "GTFO"

class GTFOLocation(Location):
    game: str = "GTFO"

class GTFORegion(Region):
    game: str = "GTFO"

    def __init__(self, name: str, player: int, multiworld: MultiWorld, hint: Optional[str] = None):
        if hint is None:
            hint = name + " !hint!" ## So I can figure out how this works
        super().__init__(name, player, multiworld, hint)
        multiworld.regions.append(self)

class GTFORegionZ(GTFORegion):
    game: str = "GTFO"
    data: ZoneData

    def __init__(self, name: str, player: int, multiworld: MultiWorld, data: ZoneData, hint: Optional[str] = None):
        super().__init__(name, player, multiworld, hint)
        self.data = data

class GTFOLevel():
    ## Note: Not a region
    name: str
    data: LevelData
    zones: List[GTFORegionZ]

    def __init__(self, name: str, data: LevelData, zones: List[GTFORegionZ]):
        self.name = name
        self.data = data
        self.zones = zones


class GTFORegionEx(GTFORegion):
    main_level: GTFOLevel
    secondary_level: Optional[GTFOLevel]
    overload_level: Optional[GTFOLevel]
    dimension_levels: Dict[int, GTFOLevel]

    def __init__(self, 
           name: str, player: int, multiworld: MultiWorld, 
           main: GTFOLevel, secondary: Optional[GTFOLevel], overload: Optional[GTFOLevel],
           dimensions: Dict[int, GTFOLevel], hint: Optional[str] = None):
        super().__init__(name, player, multiworld, hint)
        self.main_level = main
        self.secondary_level = secondary
        self.overload_level = overload
        self.dimension_levels = dimensions



class GTFOSettings(settings.Group):
    """Settings class for GTFO (unused)"""

class GTFOWeb(WebWorld):
    """
    WebWorld for GTFO
    """
    
    #options_page
    #"""A custom options page, instead of an autogenerated one"""

    rich_text_options_doc = True
    """Allow options doc strings to contain rich text formatting, which will be processed on autogenerated options pages"""

    theme = "stone"
    """Theme for this World's AP pages"""

    bug_report_page = "https://github.com/RoboRyGuy/Archipelago-GTFO/issues"
    """Webpage users can report bugs to"""


    #setup_en = Tutorial(
    #    "Multiworld Setup Guide",
    #    "A guide to setting up the Archipelago GTFO randomizer on your computer.",
    #    "English",
    #    "setup_en.md",
    #    "setup/en",
    #    ["RoboRyguy"]
    #)
    #tutorials = [setup_en]
    #"""List of Tutorial classes representing generated guides for this World"""

    game_info_langues = [ "en" ]
    """List of language codes for game info pages"""

    #options_presets
    #"""Dictionary of dictionaries mapping preset names to options and their values"""

    #location_descriptions = {
    #    "Red Potion #6": "In a secret destructible block under the second stairway",
    #    "L2 Spaceship": """
    #      The group of all items in the spaceship in Level 2.
    #
    #      This doesn't include the item on the spaceship door, since it can be
    #      accessed without the Spaceship Key.
    #    """
    #}
    #"""Maps locations to human-friendly descriptions, providing more info on where to find the location referenced"""
    
    #item_descriptions = {
    #    "Red Potion": "A standard health potion",
    #    "Spaceship Key": """
    #      The key to the spaceship in Level 2.
    #
    #      This is necessary to get to the Star Realm.
    #    """,
    #}
    #"""Maps items to human-friendly descriptions, providing more info on what the item is / does"""

    options_groups = gtfo_option_groups


class GTFOWorld(World):
    """
    GTFO is a cooperative first-person shooter developed by 10 Chambers. 
    Teams of 4 players take on the role of prisoners forced to explore a vast underground complex filled with 
    terrifying creatures. 
    Working together, they must use stealth, teamwork, and limited resources to survive expeditions, solve 
    objectives, and escape with valuable artifacts.
    """

    ## TODO: Add artifact support

    game = "GTFO"
    options_dataclass = GTFOOptions
    options: GTFOOptions
    topology_present = False; ## No path to require locations

    ## By default, we have no items or locations. All items and locations are generated as events
    item_name_to_id = {}
    location_name_to_id = {}

    modded_instance_data: ModdedInstanceData
    required_expeditions: List[ExpeditionData] = []
    filler_weights: List[float] = []
    trap_weights: List[float] = []

    @classmethod
    def get_modded_game_data_path(cls) -> str:
        """
        Path to the modded game data. "Modded game data" is the game data we need to generate with respect
        to all mods currently installed. It includes info like available expeditions, how many terminals and
        about how many artifacts are available in those expeditions, optional traps and checks to use, and
        so forth.
        """
        return Utils.local_path("gtfo_data.json")

    @classmethod
    def stage_assert_generate(cls, multiworld: "MultiWorld") -> None:
        """
        Checks that a game is capable of generating, such as checking for some base file like a ROM.
        This gets called once per present world type. Not run for unittests since they don't produce output.
        """
        assert (os.path.isfile(GTFOWorld.get_modded_game_data_path()))

    def generate_early(self) -> None:
        """
        Run before any general steps of the MultiWorld other than options. Useful for getting and adjusting option
        results and determining layouts for entrance rando etc. start inventory gets pushed after this step.
        """

        ## Load modded instance data
        try:
            with open(GTFOWorld.get_modded_game_data_path(), "r") as modded_data:
                self.modded_instance_data = ModdedInstanceData(json.load(modded_data))
        except:
            raise

        ## Find all required expeditions
        req_expedition_names : List[str] = list(map(lambda s: s.lower(), self.options.required_expeditions.value))
        found_expedition_names : List[str] = []
        self.required_expeditions = []
        
        for exp in self.modded_instance_data.expeditions:
            if exp.name in req_expedition_names:
                self.required_expeditions.append(exp)
                found_expedition_names.append(exp.name)

        for name in req_expedition_names:
            if not name in found_expedition_names:
                raise Exception(f"Missing expedition {name}")

        ## "Gaussian Kernel Weighting" for trap randomization. Idk, I'm just copying google
        ## Precomputed here to save cycles during filler and trap generation
        total_weight: float
        total_weight = 0.0
        self.filler_weights = []
        for filler in self.modded_instance_data.filler_items:
            total_weight += filler.weight
            self.filler_weights.append(total_weight)

        total_weight = 0.0
        self.trap_weights = []
        target_weight = self.options.trap_weight.value
        for trap in self.modded_instance_data.trap_items:
            sample_weight: float = math.pow(math.e, -math.pow(trap.weight - target_weight, 2) / 0.5)
            total_weight += sample_weight
            self.trap_weights.append(total_weight)


    def create_regions(self) -> None:
        """Method for creating and connecting regions for the World."""
        """We're going to do basically all our work in this one function"""

        ## Menu region
        ex_region = GTFORegionEx()

        menu_region = GTFORegion("Menu", self.player, self.multiworld)

        for ex_data in self.required_expeditions:
            expedition_region = self.create_expedition_region(ex_data)


    def create_expedition_region(self, ex_data: ExpeditionData) -> GTFORegion:
        """Create regions for an expedition. Returns the first region in the expedition"""

        ex_region = GTFORegion(f"{ex_data.name} (Expedition)", self.player, self.multiworld)
        
        def make_level(l: LevelData, s: str) -> List[GTFORegion]:
            return [ 
                GTFORegion(
                    f"{ex_data.name} ({s}) ZONE_{z_data.alias}", 
                    self.player, 
                    self.multiworld
                ) for z_data in l.zones 
            ]

        main_level = make_level(ex_data.main_level, "Main")
        secondary_level = make_level(ex_data.main_level, "Secondary")
        overload_level = make_level(ex_data.main_level, "Overload")
        dimension_levels = {
            k: make_level(v, f"Dimension #{k}") for k, v in ex_data.dimension_data.items()
        }

        levels = [main_level, secondary_level, overload_level]

        for level in itertools.chain(levels, dimension_levels.values()):

            for z_data in l_data.zones:



            pass
        ## Process events and stuff for each level

        return ex_region


    def decouple_item(self, loc: GTFOLocation, item: GTFOItem):
        """
        Given an item and its normal location, decide whether to submit both to the multiworld or
        to lock the item to its location.
        """
        ## TODO: Probably replace this with actual code at some point
        loc.place_locked_item(item)


    def create_item(self, item_name: str) -> GTFOItem:
        """
        Create an item for this world type and player.
        Warning: this may be called with self.world = None, for example by MultiServer
        """
        classification: ItemClassification = ItemClassification.filler
        if item_name.startswith("unlock_expedition"):
            classification = ItemClassification.progression
        return GTFOItem(item_name, classification, None, self.player)

    def create_filler(self) -> GTFOItem:
        ran: float = self.random.random()
        if ran < self.trap_percent:
            choice = self.random.choices(self.modded_instance_data.traps, cum_weights=self.trap_weights, k=1)[0]
            return GTFOItem(choice.name, ItemClassification.trap, None, self.player)
        else:
            choice = self.random.choices(self.modded_instance_data.fillers, cum_weights=self.trap_weights, k=1)[0]
            return GTFOItem(choice.name, ItemClassification.filler, None, self.player)

    def create_items(self) -> None:
        """
        Method for creating and submitting items to the itempool. Items and Regions must *not* be created and submitted
        to the MultiWorld after this step. If items need to be placed during pre_fill use `get_pre_fill_items`.
        """
        used_locations = 0
        if self.options.lock_expeditions.value:
            for expedition_name in self.required_expeditions:
                self.multiworld.itempool.append(
                    GTFOItem(f"unlock_expedition_{expedition_name}", ItemClassification.progression, None, self.player)
                )
                used_locations += 1

        if self.options.lock_gear.value:
            for gear_name in self.modded_instance_data.gear_names:
                if gear_name in self.options.starting_gear.value:
                    continue
                self.multiworld.itempool.append(
                    GTFOItem(f"unlock_gear_{gear_name}", ItemClassification.useful, None, self.player)
                )
                used_locations += 1

        for _ in range(self.options.lock_player_slots):
            self.multiworld.itempool.append(
                GTFOItem("unlock_player_slot", ItemClassification.useful, None, self.player)
            )
            used_locations += 1

        filler_count: int = self.location_count - used_locations
        if filler_count < 0:
            raise "Unexpected failure: insufficient locations during GTFO generation!"
        self.multiworld.itempool += [ self.create_filler() for _ in range(filler_count) ]


    #def set_rules(self) -> None:
    #    """Method for setting the rules on the World's regions and locations."""
    #    ## Rules are set during create_regions
    #    pass

    #def connect_entrances(self) -> None:
    #    """Method to finalize the source and target regions of the World's entrances"""
    #    pass

    #def generate_basic(self) -> None:
    #    """
    #    Useful for randomizing things that don't affect logic but are better to be determined before the output stage.
    #    i.e. checking what the player has marked as priority or randomizing enemies
    #    """
    #    pass

    #def pre_fill(self) -> None:
    #    """Optional method that is supposed to be used for special fill stages. This is run *after* plando."""
    #    pass

    #def fill_hook(self,
    #              progitempool: List["Item"],
    #              usefulitempool: List["Item"],
    #              filleritempool: List["Item"],
    #              fill_locations: List["Location"]) -> None:
    #    """Special method that gets called as part of distribute_items_restrictive (main fill)."""
    #    pass

    #def post_fill(self) -> None:
    #    """
    #    Optional Method that is called after regular fill. Can be used to do adjustments before output generation.
    #    This happens before progression balancing, so the items may not be in their final locations yet.
    #    """
    #    pass

    #def generate_output(self, output_directory: str) -> None:
    #    """
    #    This method gets called from a threadpool, do not use multiworld.random here.
    #    If you need any last-second randomization, use self.random instead.
    #    """
    #    pass

    def fill_slot_data(self) -> Mapping[str, Any]:  # json of WebHostLib.models.Slot
        """
        What is returned from this function will be in the `slot_data` field
        in the `Connected` network package.
        It should be a `dict` with `str` keys, and should be serializable with json.

        This is a way the generator can give custom data to the client.
        The client will receive this as JSON in the `Connected` response.

        The generation does not wait for `generate_output` to complete before calling this.
        `threading.Event` can be used if you need to wait for something from `generate_output`.
        """
        # The reason for the `Mapping` type annotation, rather than `dict`
        # is so that type checkers won't worry about the mutability of `dict`,
        # so you can have more specific typing in your world implementation.

        return {
            "required_expeditions": [ exp.name for exp in self.required_expeditions ],
            "lock_expeditions": self.options.lock_expeditions.value,
            "lock_gear": self.options.lock_gear.value,
            "lock_player_slots": self.options.lock_player_slots.value,
        }

    #def extend_hint_information(self, hint_data: Dict[int, Dict[int, str]]):
    #    """
    #    Fill in additional entrance information text into locations, which is displayed when hinted.
    #    structure is {player_id: {location_id: text}} You will need to insert your own player_id.
    #    """
    #    pass

    #def modify_multidata(self, multidata: "MultiData") -> None:
    #    """For deeper modification of server multidata."""
    #    pass

    # Spoiler writing is optional, these may not get called.
    #def write_spoiler_header(self, spoiler_handle: TextIO) -> None:
    #    """
    #    Write to the spoiler header. If individual it's right at the end of that player's options,
    #    if as stage it's right under the common header before per-player options.
    #    """
    #    pass

    #def write_spoiler(self, spoiler_handle: TextIO) -> None:
    #    """
    #    Write to the spoiler "middle", this is after the per-player options and before locations,
    #    meant for useful or interesting info.
    #    """
    #    pass

    #def write_spoiler_end(self, spoiler_handle: TextIO) -> None:
    #    """Write to the end of the spoiler"""
    #    pass

