from __future__ import annotations
from pydantic import BaseModel, Field
from typing import List, Literal, Mapping, Optional, Union

"""
The `Gen_` prefix applied to clases in this file is purely to prevent naming overlap,
and is not because the classes were autogenerated.
 -> I would like to autogenerate these, but for now they're manually created :)
"""

class Gen_GameData(BaseModel):
    name: Optional[str]                   = Field(alias="Name")
    expeditions: List[Gen_ExpeditionData] = Field(alias="Expeditions")
    tags: List[Gen_Tag]                   = Field(alias="Tags")
    regions: List[Gen_Region]             = Field(alias="Regions")
    paths: List[Gen_Path]                 = Field(alias="Paths")
    locations: List[Gen_Location]         = Field(alias="Locations")
    items: List[Gen_Item]                 = Field(alias="Items")
    floating_items: List[int]             = Field(alias="FloatingItems")
    options: List[Gen_Option]             = Field(alias="Options")

class Gen_ExpeditionData(BaseModel):
    name: str                    = Field(alias="Name")
    reachable_regions: List[int] = Field(alias="ReachableRegions")

class Gen_Tag(BaseModel):
    id: int          = Field(alias="ID")
    name: str        = Field(alias="Name")
    description: str = Field(alias="Description")
    parent: int      = Field(alias="Parent")

class Gen_Region(BaseModel):
    id: int   = Field(alias="ID")
    name: str = Field(alias="Name")

class Gen_ReqItem(BaseModel):
    type: str   = Field(alias="Type")
    target: int = Field(alias="Target")

class Gen_Path(BaseModel):
    id: int               = Field(alias="ID")
    name: Optional[str]   = Field(alias="Name")
    starting_region: int  = Field(alias="StartingRegion")
    ending_region: int    = Field(alias="EndingRegion")
    req_item: Gen_ReqItem = Field(alias="ReqItem")
    req_count: int        = Field(alias="ReqCount")
    alt_item: Gen_ReqItem = Field(alias="AlternateItem")

class Gen_LocationData(BaseModel):
    priority_mode: str = Field(alias="PriorityMode")
    is_empty: bool     = Field(alias="IsEmpty")

class Gen_Location(BaseModel):
    id: int                     = Field(alias="ID")
    name_tag: int               = Field(alias="NameTag")
    tag2: int                   = Field(alias="Tag2")
    tag3: int                   = Field(alias="Tag3")
    rand_data: Gen_LocationData = Field(alias="RandData")
    item_id: int                = Field(alias="ItemID")
    owning_regions: List[int]   = Field(alias="OwningRegionIds")
    is_randomized: bool         = Field(alias="IsRandomized", default=False)

    def __hash__(self):
        return hash(f"Location {self.id}")

class Gen_ItemData(BaseModel):
    is_progression: bool       = Field(alias="IsProgression")
    is_useful: bool            = Field(alias="IsUseful")
    is_filler: bool            = Field(alias="IsFiller")
    is_trap: bool              = Field(alias="IsTrap")
    do_skip_balancing: bool    = Field(alias="DoSkipBalancing")
    is_deprioritized: bool     = Field(alias="IsDeprioritized")
    collected_by_default: bool = Field(alias="CollectedByDefault")

class Gen_Item(BaseModel):
    id: int                            = Field(alias="ID")
    name_tag: int                      = Field(alias="NameTag")
    tag2: int                          = Field(alias="Tag2")
    tag3: int                          = Field(alias="Tag3")
    rand_data: Gen_ItemData            = Field(alias="RandData")
    path_reqs: Gen_ReqItem             = Field(alias="PathReqs")
    required_expedition: Optional[str] = Field(alias="RequiredExpeditionName")
    is_randomized: bool                = Field(alias="IsRandomized", default=False)

    def __hash__(self):
        return hash(f"Item {self.id}")

class Gen_Option(BaseModel):
    type: str                                      = Field(alias="Type")
    name: str                                      = Field(alias="Name")
    category: str                                  = Field(alias="Category")
    description: str                               = Field(alias="Description")
    default_value: str                             = Field(alias="DefaultValue")
    choices: Mapping[str, Mapping[str, List[int]]] = Field(alias="Choices")
