from worlds.AutoWorld import WebWorld

## Not sure I need or even use this
class GTFOWeb(WebWorld):
    """
    WebWorld for GTFO
    """
    
    #options_page
    #"""A custom options page, instead of an autogenerated one"""

    rich_text_options_doc = True
    """
    Allow options doc strings to contain rich text formatting, which will be processed on autogenerated options pages
    """

    theme = "stone"
    """Theme for this World's AP pages"""

    bug_report_page = "https://github.com/RoboRyGuy/Archipelago-GTFO/issues"
    """Webpage users can report bugs to"""


    #setup_en = Tutorial(
    #    "Multiworld Setup Guide",
    #    "A guide to setting up the Archipelago GTFO randomizer on your computer.",
    #    "English",
    #    "setup_en.md",
    #    "setup/en",
    #    ["RoboRyguy"]
    #)
    #tutorials = [setup_en]
    #"""List of Tutorial classes representing generated guides for this World"""

    game_info_langues = [ "en" ]
    """List of language codes for game info pages"""

    #options_presets
    #"""Dictionary of dictionaries mapping preset names to options and their values"""

    #location_descriptions = {
    #    "Red Potion #6": "In a secret destructible block under the second stairway",
    #    "L2 Spaceship": """
    #      The group of all items in the spaceship in Level 2.
    #
    #      This doesn't include the item on the spaceship door, since it can be
    #      accessed without the Spaceship Key.
    #    """
    #}
    #"""Maps locations to human-friendly descriptions, providing more info on where to find the location referenced"""
    
    #item_descriptions = {
    #    "Red Potion": "A standard health potion",
    #    "Spaceship Key": """
    #      The key to the spaceship in Level 2.
    #
    #      This is necessary to get to the Star Realm.
    #    """,
    #}
    #"""Maps items to human-friendly descriptions, providing more info on what the item is / does"""

    options_groups = gtfo_option_groups
